-- Generated by DOKU_SECRETS_SETUP.md
-- Safe template only: keep placeholders, never commit real secrets.

-- Replace placeholders before execution:
-- __VENUE_ID__ integer venue id (example: 6)
-- __ENVIRONMENT__ sandbox|production
-- __BUSINESS_ID__
-- __BRAND_ID__
-- __MERCHANT_ID__
-- __API_KEY__
-- __CLIENT_ID__
-- __SECRET_KEY__
-- __CHECKOUT_BASE_URL__
-- __DOKU_PUBLIC_KEY__
-- __MERCHANT_PUBLIC_KEY__

insert into public.doku_venue_config (
  venue_id,
  environment,
  business_id,
  brand_id,
  merchant_id,
  api_key,
  client_id,
  secret_key,
  checkout_base_url,
  doku_public_key,
  merchant_public_key,
  updated_at
)
values (
  __VENUE_ID__,
  '__ENVIRONMENT__',
  '__BUSINESS_ID__',
  '__BRAND_ID__',
  '__MERCHANT_ID__',
  '__API_KEY__',
  '__CLIENT_ID__',
  '__SECRET_KEY__',
  '__CHECKOUT_BASE_URL__',
  '__DOKU_PUBLIC_KEY__',
  '__MERCHANT_PUBLIC_KEY__',
  now()
)
on conflict (venue_id)
do update set
  environment = excluded.environment,
  business_id = excluded.business_id,
  brand_id = excluded.brand_id,
  merchant_id = excluded.merchant_id,
  api_key = excluded.api_key,
  client_id = excluded.client_id,
  secret_key = excluded.secret_key,
  checkout_base_url = excluded.checkout_base_url,
  doku_public_key = excluded.doku_public_key,
  merchant_public_key = excluded.merchant_public_key,
  updated_at = now();
